import type { ThemeConfig } from "antd";

export const modernTheme: ThemeConfig = {
  token: {
    colorPrimary: "#3b73e5",
    colorSuccess: "#16a34a",
    colorWarning: "#d97706",
    colorError: "#dc2626",
    colorInfo: "#3b73e5",
    fontFamily: `"Segoe UI","SF Pro Text","PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif`,
    fontSize: 14,
    borderRadius: 8,
    borderRadiusLG: 10,
    borderRadiusSM: 6,
    boxShadow: "0 12px 28px rgba(37, 51, 72, 0.06)",
    boxShadowSecondary: "0 20px 48px rgba(37, 51, 72, 0.1)",
    padding: 16,
    margin: 16,
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBgLayout: "#f4f7fb",
    colorBorder: "#dce4ee",
    colorBorderSecondary: "#edf1f5",
    colorText: "#19243a",
    colorTextSecondary: "#65748a",
    colorTextTertiary: "#8b99ab",
    colorTextQuaternary: "#a7b2c1",
    colorLink: "#3b73e5",
    colorLinkHover: "#285fca",
    colorLinkActive: "#214fa9",
  },
  components: {
    Button: {
      controlHeight: 38,
      controlHeightLG: 44,
      controlHeightSM: 32,
      fontWeight: 600,
      borderRadius: 8,
      primaryShadow: "0 8px 18px rgba(59, 115, 229, 0.18)",
      defaultBg: "#ffffff",
      defaultBorderColor: "#dce4ee",
      defaultColor: "#19243a",
    },
    Input: {
      controlHeight: 38,
      controlHeightLG: 44,
      controlHeightSM: 32,
      paddingBlock: 8,
      paddingBlockLG: 10,
      paddingBlockSM: 8,
      activeBorderColor: "#3b73e5",
      hoverBorderColor: "#3b73e5",
      colorBgContainer: "#ffffff",
    },
    Select: {
      controlHeight: 38,
      controlHeightLG: 44,
      controlHeightSM: 32,
      colorBgContainer: "#ffffff",
    },
    Card: {
      borderRadiusLG: 10,
      paddingLG: 24,
    },
    Modal: {
      borderRadiusLG: 12,
    },
    Message: {
      contentBg: "#ffffff",
      contentPadding: "12px 16px",
    },
    Tag: {
      borderRadiusSM: 999,
    },
    Layout: {
      headerBg: "#f4f7fb",
      headerHeight: 72,
      headerPadding: "0",
      siderBg: "#202b3b",
      bodyBg: "#f4f7fb",
    },
    Table: {
      borderColor: "#edf1f5",
      headerBg: "#f8fafc",
      headerColor: "#65748a",
      rowHoverBg: "#f8fafc",
    },
  },
};
export const whatsappTheme: ThemeConfig = {
  token: {
    colorPrimary: "#25D366",
    colorSuccess: "#25D366",
    colorBgContainer: "#FFFFFF",
    colorBgLayout: "#F0F2F5",
    borderRadius: 8,
    fontFamily: `"IBM Plex Sans","PingFang SC","Hiragino Sans GB","Microsoft YaHei","Segoe UI",sans-serif`,
  },
  components: {
    Layout: {
      headerBg: "#FFFFFF",
      siderBg: "#FFFFFF",
      bodyBg: "#F0F2F5",
    },
  },
};
