server.port=8091
request.path=/api


sqlconn = user_AK:aK7AatZ7f6G389YkA@tcp(rm-1udp284ed63ryc72swo.mysql.rds.aliyuncs.com:3306)/surfer?charset=utf8&parseTime=True&loc=Local

log.dir=./logs/

redis.addr = r-1udhkwni3lun2qhfgrpd.redis.rds.aliyuncs.com:6379
redis.password = kA54R98e124d77i5saK

barry.base-url=http://116.62.212.29/barry-gateway-pro
barry.url.inner.prefix=http://116.62.212.29/barry-gateway-pro
## 人工商品相关
barry.url.inner.shop.suffix = /shops/shopTypes
barry.url.inner.manual.list.suffix = /shops/shopCategories
barry.url.inner.manual.save.suffix = /shops/shopCategory/save
barry.url.inner.manual.delete.suffix = /shops/shopCategory/delete
barry.url.inner.manual.expire.suffix = /shops/shopCategory/expire
barry.url.inner.manual.active.suffix = /shops/shopCategory/active

## 渠道相关
barry.url.inner.channel.list.suffix = /channel/list
barry.url.inner.channel.detail.save.list.suffix = /channel/detail/save
barry.url.inner.channel.detail.update.list.suffix = /channel/detail/update
barry.url.inner.channel.detail.list.suffix = /channel/detail/list

##人工积分相关
barry.url.inner.point.withdraw.summary.suffix = /point/withdrawSummary?channel={channel}&startTime={startTime}&endTime={endTime}
barry.url.inner.record.summary.suffix = /order/summary?code={code}&sumDate={sumDate}
barry.url.inner.point.withdraw.summary.account.suffix = /point/withdrawSummary/account?channel={channel}&startTime={startTime}&endTime={endTime}
barry.url.inner.point.withdraw.summary.finish.suffix = /point/withdrawSummary/finish?channel={channel}&startTime={startTime}&endTime={endTime}


## 人工用户管理
barry.url.inner.user.detail.find.suffix = /user/detail?username={username}
barry.url.inner.user.detail.save.suffix = /user/detail/save
barry.url.inner.user.detail.update.suffix = /user/detail/update
barry.url.inner.user.detail.list.suffix = /user/detail/list

## 人工提现
barry.url.inner.point.user.withdraw.record.suffix = /point/user/withdrawRecord?username={username}&channel={channel}&status={status}&startTime={startTime}&endTime={endTime}
barry.url.inner.point.user.withdraw.account.suffix = /point/user/withdraw/account
barry.url.inner.point.user.withdraw.finish.suffix = /point/user/withdraw/finish
barry.url.inner.point.user.withdraw.cancel.suffix = /point/user/withdraw/cancel
