server.port=7091
request.path=/api


sqlconn = user_AK:aK7AatZ7f6G389YkA@tcp(rm-1udp284ed63ryc72swo.mysql.rds.aliyuncs.com:3306)/surfer?charset=utf8&parseTime=True&loc=Local

log.dir=./logs/

redis.addr = r-1udhkwni3lun2qhfgrpd.redis.rds.aliyuncs.com:6379
redis.password = kA54R98e124d77i5saK




# barry.base-url=http://116.62.212.29/barry-gateway-pro
# barry.url.inner.prefix=http://116.62.212.29/barry-gateway-pro

barry.base-url=http://localhost:9998
barry.url.inner.prefix=http://localhost:9998
## 人工商品相关
barry.url.inner.shop.suffix = /shops/shopTypes
barry.url.inner.manual.list.suffix = /shops/shopCategories
barry.url.inner.manual.save.suffix = /shops/shopCategory/save
barry.url.inner.manual.delete.suffix = /shops/shopCategory/delete
barry.url.inner.manual.expire.suffix = /shops/shopCategory/expire
barry.url.inner.manual.active.suffix = /shops/shopCategory/active
barry.url.inner.assign.config.list.suffix = /assignConfigs
barry.url.inner.assign.config.save.suffix = /assignConfigs/save
barry.url.inner.judge.config.list.suffix = /judgeConfigs
barry.url.inner.judge.config.save.suffix = /judgeConfigs/save
barry.url.inner.assign.uid.rule.get.suffix = /assignUidRules
barry.url.inner.assign.uid.rule.save.suffix = /assignUidRules/save
barry.url.inner.assign.video.rule.get.suffix = /assignVideoRules
barry.url.inner.assign.video.rule.save.suffix = /assignVideoRules/save
barry.url.inner.assign.refund.rule.get.suffix = /assignRefundRules
barry.url.inner.assign.refund.rule.save.suffix = /assignRefundRules/save
barry.url.inner.assign.video.user.rule.list.suffix = /assignVideoUserRules
barry.url.inner.assign.video.user.rule.save.suffix = /assignVideoUserRules/save
barry.url.inner.assign.video.user.rule.delete.suffix = /assignVideoUserRules/delete
barry.url.inner.assign.whitelist.switch.get.suffix = /assignWhitelistSwitch
barry.url.inner.assign.whitelist.switch.save.suffix = /assignWhitelistSwitch/save
barry.url.inner.assign.uid.switch.get.suffix = /assignUidSwitch
barry.url.inner.assign.uid.switch.save.suffix = /assignUidSwitch/save
barry.url.inner.app.user.list.suffix = /appUser/list
barry.url.inner.user.whitelist.list.suffix = /user/whitelist/list
barry.url.inner.user.whitelist.save.suffix = /user/whitelist/save
barry.url.inner.user.whitelist.active.suffix = /user/whitelist/active
barry.url.inner.user.whitelist.group.suffix = /user/whitelist/group

## 渠道相关
barry.url.inner.channel.list.suffix = /channel/list
barry.url.inner.channel.detail.save.list.suffix = /channel/detail/save
barry.url.inner.channel.detail.update.list.suffix = /channel/detail/update
barry.url.inner.channel.detail.list.suffix = /channel/detail/list

##人工积分相关
barry.url.inner.point.withdraw.summary.suffix = /point/withdrawSummary?channel={channel}&startTime={startTime}&endTime={endTime}
barry.url.inner.record.summary.suffix = /order/summary?code={code}&sumDate={sumDate}
barry.url.inner.manual.task.statistics.suffix = /manual/task-statistics
barry.url.inner.manual.order.details.suffix = /manual/order-details
barry.url.inner.manual.order.details.sec.uid.suffix = /manual/order-details/sec-uid
barry.url.inner.statistics.suffix = /order/statistics
barry.workbench.dashboard.manual.submitted.group.code = MI_MIN_LOVE
barry.url.inner.workbench.dashboard.user.overview.suffix = /workbench/dashboard/user-overview
barry.url.inner.workbench.dashboard.user.online.overview.suffix = /workbench/dashboard/user-online-overview
barry.url.inner.workbench.dashboard.task.remaining.suffix = /workbench/dashboard/task-remaining
barry.url.inner.workbench.dashboard.manual.submitted.suffix = /workbench/dashboard/manual-submitted
barry.url.inner.workbench.dashboard.manual.speed.suffix = /workbench/dashboard/manual-speed
barry.url.inner.workbench.dashboard.manual.submitted.comparison.suffix = /workbench/dashboard/manual-submitted-comparison
barry.url.inner.workbench.dashboard.actual.completed.suffix = /workbench/dashboard/actual-completed
barry.url.inner.manual.task.statistics.users.suffix = /manual/task-statistics/users
barry.url.inner.point.withdraw.summary.account.suffix = /point/withdrawSummary/account?channel={channel}&startTime={startTime}&endTime={endTime}
barry.url.inner.point.withdraw.summary.finish.suffix = /point/withdrawSummary/finish?channel={channel}&startTime={startTime}&endTime={endTime}


## 人工用户管理
barry.url.inner.user.detail.find.suffix = /user/detail?username={username}
barry.url.inner.user.detail.save.suffix = /user/detail/save
barry.url.inner.user.detail.update.suffix = /user/detail/update
barry.url.inner.user.detail.password.update.suffix = /user/detail/password
barry.url.inner.user.detail.basic.list.suffix =
barry.url.inner.user.detail.list.suffix = /user/detail/list

## 人工提现
barry.url.inner.point.user.withdraw.record.suffix = /point/user/withdrawRecord?username={username}&channel={channel}&status={status}&startTime={startTime}&endTime={endTime}
barry.url.inner.point.user.withdraw.account.suffix = /point/user/withdraw/account
barry.url.inner.point.user.withdraw.finish.suffix = /point/user/withdraw/finish
barry.url.inner.point.user.withdraw.cancel.suffix = /point/user/withdraw/cancel
