sqlconn = user_AK:aK7AatZ7f6G389YkA@tcp(rm-1udp284ed63ryc72swo.mysql.rds.aliyuncs.com:3306)/surfer?charset=utf8&parseTime=True&loc=Local

redis.addr = r-1udhkwni3lun2qhfgrpd.redis.rds.aliyuncs.com:6379
redis.password = kA54R98e124d77i5saK

order.fetch.size=100
order.handler.queue.prefix=queue
order.handler.consumer.concurrency=1
order.handler.consumer.block-timeout-seconds=3
