server.port=8092
request.path=/api

sqlconn=root:password@tcp(127.0.0.1:3306)/blade?charset=utf8mb4&parseTime=True&loc=Local

redis.addr=127.0.0.1:6379
redis.password=

blade.task.queue_name=blade_task_dispatch
blade.task.worker_parallelism=4
blade.task.max_retry=3
