#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
if [[ ${EUID} -ne 0 ]]; then exec sudo bash "$SCRIPT_DIR/deploy.sh" "$@"; fi
[[ "$(uname -s)" == Linux ]] || { echo 'Run this script on the ECS Linux host.' >&2; exit 1; }
for cmd in systemctl curl install flock; do
  command -v "$cmd" >/dev/null || { echo "Missing command: $cmd" >&2; exit 1; }
done
APP_DIR=/opt/suffer-gateway
CONFIG_DIR=/etc/suffer-gateway
CONFIG_FILE="$CONFIG_DIR/config.json"
UNIT_FILE=/etc/systemd/system/suffer-gateway.service
[[ -f "$SCRIPT_DIR/suffer-gateway" && -f "$SCRIPT_DIR/suffer-gateway.service" ]] || {
  echo 'Extract the archive generated by build.sh and run its deploy.sh.' >&2; exit 1;
}
mkdir -p "$APP_DIR/backups" "$CONFIG_DIR"
exec 9>"$APP_DIR/.deploy.lock"
flock -n 9 || { echo 'Another deployment is running.' >&2; exit 1; }

if [[ -f "$CONFIG_FILE" ]]; then
  echo "Keeping existing configuration: $CONFIG_FILE"
  CONFIG_SOURCE="$CONFIG_FILE"
else
  CONFIG_SOURCE="${1:-$SCRIPT_DIR/config.json}"
  [[ -f "$CONFIG_SOURCE" ]] || {
    echo 'First deployment: copy config.example.json to config.json, set listen to the ECS private IP, then run ./deploy.sh ./config.json' >&2
    exit 1
  }
fi
# Validate the new executable and existing configuration before stopping anything.
chmod 0755 "$SCRIPT_DIR/suffer-gateway"
"$SCRIPT_DIR/suffer-gateway" -config "$CONFIG_SOURCE" -check-config
if ! id suffer-gateway >/dev/null 2>&1; then
  useradd --system --user-group --no-create-home --shell /sbin/nologin suffer-gateway
fi
if [[ ! -f "$CONFIG_FILE" ]]; then
  install -m 0640 -o root -g suffer-gateway "$CONFIG_SOURCE" "$CONFIG_FILE"
fi

BACKUP="$(mktemp -d "$APP_DIR/backups/deploy.XXXXXXXX")"
[[ ! -f "$APP_DIR/suffer-gateway" ]] || cp -p "$APP_DIR/suffer-gateway" "$BACKUP/suffer-gateway"
[[ ! -f "$UNIT_FILE" ]] || cp -p "$UNIT_FILE" "$BACKUP/suffer-gateway.service"
WAS_ACTIVE=false
if systemctl is-active --quiet suffer-gateway.service; then WAS_ACTIVE=true; fi
rollback() {
  result=$?
  trap - ERR
  set +e
  echo "Deployment failed; restoring previous executable/service from $BACKUP" >&2
  systemctl stop suffer-gateway.service
  if [[ -f "$BACKUP/suffer-gateway" ]]; then
    install -m 0755 "$BACKUP/suffer-gateway" "$APP_DIR/suffer-gateway"
  fi
  if [[ -f "$BACKUP/suffer-gateway.service" ]]; then
    install -m 0644 "$BACKUP/suffer-gateway.service" "$UNIT_FILE"
  fi
  systemctl daemon-reload
  if [[ "$WAS_ACTIVE" == true ]]; then systemctl start suffer-gateway.service; fi
  echo 'Configuration was preserved. On a first deployment, the failed installation is left stopped for inspection.' >&2
  exit "$result"
}
trap rollback ERR
if [[ "$WAS_ACTIVE" == true ]]; then systemctl stop suffer-gateway.service; fi
install -m 0755 "$SCRIPT_DIR/suffer-gateway" "$APP_DIR/suffer-gateway.new"
mv -f "$APP_DIR/suffer-gateway.new" "$APP_DIR/suffer-gateway"
install -m 0755 "$SCRIPT_DIR/start.sh" "$APP_DIR/start.sh"
install -m 0755 "$SCRIPT_DIR/stop.sh" "$APP_DIR/stop.sh"
install -m 0644 "$SCRIPT_DIR/suffer-gateway.service" "$UNIT_FILE"
systemctl daemon-reload
bash "$APP_DIR/start.sh"
systemctl enable suffer-gateway.service
trap - ERR
echo "Deployment succeeded. Backup: $BACKUP"
echo "Logs: journalctl -u suffer-gateway.service -f"
